on: 
    push:
        branches:
            - dev
name: Deploy test website on push on branch dev
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.onto4all.com
        username: u198149674.dev
        password: Onto4@LL
        server-dir: /
