# on: 
#     push:
#         branches:
#             - master
# name: 🚀 Deploy website on push
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: 🚚 Get latest code
#       uses: actions/checkout@v2
    
#     - name: 📂 Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.3.0
#       with:
#         server: ftp.onto4all.com
#         username:  u198149674.user198149674
#         password: onto4@LL
#         server-dir: /

name: 🚀 Deploy website on push

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  push:
        branches:
            - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.onto4all.com
        username:  u198149674
        password: otnO4aLL!
        server-dir: domains/onto4all.com